"""add allocations bookings maintenance audits notifications

Revision ID: 288216f42f3a
Revises: 68f46c031470
Create Date: 2026-07-12 14:34:37.445782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288216f42f3a'
down_revision: Union[str, Sequence[str], None] = '68f46c031470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('asset_allocations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('allocated_by_id', sa.String(length=50), nullable=False),
    sa.Column('allocation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['allocated_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_allocations_id'), 'asset_allocations', ['id'], unique=False)
    op.create_index('uix_active_allocation_per_asset', 'asset_allocations', ['asset_id'], unique=True, postgresql_where=sa.text("status = 'Active'"))
    op.create_table('asset_bookings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_bookings_id'), 'asset_bookings', ['id'], unique=False)
    op.create_index('ix_booking_asset_dates', 'asset_bookings', ['asset_id', 'start_time', 'end_time'], unique=False)
    # PostgreSQL enforces the overlap rule at the database level.  SQLite is
    # used by the local checkpoint suite and does not support GiST/exclusion
    # constraints, so it continues to rely on the application-level check.
    if op.get_bind().dialect.name == "postgresql":
        op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist;')
        op.execute('''
            ALTER TABLE asset_bookings
            ADD CONSTRAINT no_overlapping_approved_bookings
            EXCLUDE USING gist (
                asset_id WITH =,
                tstzrange(start_time, end_time, '[)') WITH &&
            )
            WHERE (status = 'Approved');
        ''')
    op.create_table('asset_transfers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('from_employee_id', sa.String(length=50), nullable=False),
    sa.Column('to_employee_id', sa.String(length=50), nullable=False),
    sa.Column('requested_by_id', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.String(length=50), nullable=True),
    sa.Column('request_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transfers_id'), 'asset_transfers', ['id'], unique=False)
    op.create_table('audit_cycles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initiated_by_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_cycles_id'), 'audit_cycles', ['id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('requested_by_id', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('issue_description', sa.String(length=500), nullable=False),
    sa.Column('resolution_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('audit_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('audit_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scanned_by_id', sa.String(length=50), nullable=True),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ),
    sa.ForeignKeyConstraint(['scanned_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_items_id'), 'audit_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_items_id'), table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_audit_cycles_id'), table_name='audit_cycles')
    op.drop_table('audit_cycles')
    op.drop_index(op.f('ix_asset_transfers_id'), table_name='asset_transfers')
    op.drop_table('asset_transfers')
    op.drop_index('ix_booking_asset_dates', table_name='asset_bookings')
    op.drop_index(op.f('ix_asset_bookings_id'), table_name='asset_bookings')
    if op.get_bind().dialect.name == "postgresql":
        op.execute('ALTER TABLE asset_bookings DROP CONSTRAINT IF EXISTS no_overlapping_approved_bookings;')
    op.drop_table('asset_bookings')
    op.drop_index('uix_active_allocation_per_asset', table_name='asset_allocations', postgresql_where=sa.text("status = 'Active'"))
    op.drop_index(op.f('ix_asset_allocations_id'), table_name='asset_allocations')
    op.drop_table('asset_allocations')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
