"""add_extended_backend_features

Revision ID: 668b1171fc47
Revises: 288216f42f3a
Create Date: 2026-07-12 15:31:52.904657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668b1171fc47'
down_revision: Union[str, Sequence[str], None] = '288216f42f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('audit_cycle_auditors',
    sa.Column('audit_cycle_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_cycle_id', 'employee_id')
    )
    op.add_column('asset_allocations', sa.Column('department_id', sa.String(length=50), nullable=True))
    op.add_column('asset_allocations', sa.Column('expected_return_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset_allocations', sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('asset_allocations', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'asset_allocations', 'departments', ['department_id'], ['id'])
    op.create_check_constraint(
        'chk_employee_xor_department',
        'asset_allocations',
        '(employee_id IS NOT NULL AND department_id IS NULL) OR (employee_id IS NULL AND department_id IS NOT NULL)'
    )
    op.add_column('asset_bookings', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_cycles', sa.Column('scope_department_id', sa.String(length=50), nullable=True))
    op.add_column('audit_cycles', sa.Column('scope_category_id', sa.String(length=50), nullable=True))
    op.add_column('audit_cycles', sa.Column('scope_location', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'audit_cycles', 'categories', ['scope_category_id'], ['id'])
    op.create_foreign_key(None, 'audit_cycles', 'departments', ['scope_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_cycles', type_='foreignkey')
    op.drop_constraint(None, 'audit_cycles', type_='foreignkey')
    op.drop_column('audit_cycles', 'scope_location')
    op.drop_column('audit_cycles', 'scope_category_id')
    op.drop_column('audit_cycles', 'scope_department_id')
    op.drop_column('asset_bookings', 'reminder_sent_at')
    op.drop_constraint('chk_employee_xor_department', 'asset_allocations', type_='check')
    op.drop_constraint(None, 'asset_allocations', type_='foreignkey')
    op.alter_column('asset_allocations', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('asset_allocations', 'overdue_notified_at')
    op.drop_column('asset_allocations', 'expected_return_date')
    op.drop_column('asset_allocations', 'department_id')
    op.drop_table('audit_cycle_auditors')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
